### ISSUE TITLE
Error building certpath

### ISSUE THREAD

**Issue by atumminia** [jariq/Pkcs7SignatureGenerator#2]
Hi, i got this error while building certpath while signing a file

![errore per jariq](https://user-images.githubusercontent.com/36635775/36493049-e8acd470-172e-11e8-892c-9bb64d300f99.png)

`List<byte[]> otherCertificates = pkcs7.GetAllCertificates();
ICollection<Org.BouncyCastle.X509.X509Certificate> certPath = CertUtils.BuildCertPath(CertCKA, otherCertificates,false);`

thank you

**Comment by jariq** [comment]
CertUtils.BuildCertPath() method builds the whole certificate chain up to a root certificate which is always self-signed.

**Comment by atumminia** [comment]
Hi, i try to write an example to explain my case:

I have 1 User Certificate and 2 User Keys (Public and Private)

this is my function to generate pkcs7
`pkcs7=Pkcs7SignatureGenerator(Library,_selectedSlot.TokenInfo.SerialNumber,_selectedSlot.TokenInfo.Label,pin,PrivateKey.CkaLabel,PrivateKey.CkaId,HashAlgorithm.SHA256,SignatureScheme.RSASSA_PKCS1_v1_5);`

now i take all certificate from pkcs7
`List<byte[]> otherCertificates = pkcs7.GetAllCertificates();`

and in the end
`ICollection<Org.BouncyCastle.X509.X509Certificate> certPath = CertUtils.BuildCertPath(UserCertificate.CkaValue, otherCertificates ,true);`

when i run my application i got this error
![errore per jariq](https://user-images.githubusercontent.com/36635775/36531702-0b9d0974-17bf-11e8-8ab3-4ad9977dff51.png)

What should I do to correct this error?

thank you

**Comment by jariq** [comment]
In this case `pkcs7.GetAllCertificates();` returns all certificates stored on your token/card. Import CA certificates on your card and let me know the result.

**Comment by atumminia** [comment]
Hi, this is my code for import CA 
```
List<byte[]> otherCertificates = new List<byte[]>();
byte[] certUnobyte = File.ReadAllBytes("C:\\temp\\InfoCert_Servizi_di_Certificazione.cer");
byte[] certDuebyte = File.ReadAllBytes("C:\\temp\\InfoCert_Servizi_di_Certificazione_2.cer");
otherCertificates.Add(certUnobyte);
otherCertificates.Add(certDuebyte);

ICollection<Org.BouncyCastle.X509.X509Certificate> certPath = CertUtils.BuildCertPath(CertCKA, otherCertificates,true);
``` 

this is the error i got

![2error](https://user-images.githubusercontent.com/36635775/36718601-ae3010e6-1ba2-11e8-9905-2c03bccd3a6d.png)

**Comment by jariq** [comment]
You are most likely not importing all CAs (up to root CA) forming the certification path or you are importing incorrect ones.

**Comment by atumminia** [comment]
how can i do to import all the certificates?

**Comment by jariq** [comment]
Can you post your certificate here?

**Comment by atumminia** [comment]
CA certificate or my.cer certificate?

**Comment by jariq** [comment]
Ideally all of them.

**Comment by pratik-agrawalla** [comment]
Hi, I want to generate CADES-BES signature . I have a precomputed signature from HSM Key vault. I want to create a CADES-BES structure that contains it.   With this code i am getting CMS type signature and it is not supported as per my requirement.

**Comment by jariq** [comment]
Closing because of 5 years without an activity 😄
