### ISSUE TITLE
CKA_Value could not be read

### ISSUE THREAD

**Issue by AbhishekPandey16** [jariq/Pkcs7SignatureGenerator#3]
Hi, 

I am trying to generate the CMS Pkcs7 signature. The sample code states that we have to read the CKA_VALUE to get the certificate information. However my HSM device restricts me to read the certificate information due to security reason. 
Is there any other value to get this through?

Thanks,
Abhishek

**Comment by jariq** [comment]
You'd have to modify the code yourself to read the certificate from any other source for example from file.

**Comment by AbhishekPandey16** [comment]
Thanks for the response Jariq. 
Apologies for not understanding it correctly. The certificate is not exportable. When you said read it from file did you mean to export and then read from disk file? Will be great if you can please attach a sample code for reference .

**Comment by AbhishekPandey16** [comment]
Issue got fixed while following the correct order of the  signature
