### ISSUE TITLE
Signature verification failes with hash value not correct 

### ISSUE THREAD

**Issue by AbhishekPandey16** [jariq/Pkcs7SignatureGenerator#4]
Hi, 
I am trying to generate the cms signed pkcs7mesaage using SHA256. I am using the scheme RSASSA_pkcs1_v1_5.
I am refering the code here and able to generate the signature. How ever when I am trying to verify it, it says the hash value not correct. I am simply generating the signature and passing the signature dump with data to below. No tampering possible.

var signedcms = new SignedCms(new contentinfo(data), true);
signedcms.Decode(signaturedump);
signedcms.CheckSignature(signaturecertificate x509certificate2 object, true) 

What can possibly go wring here ? Request a kind help

**Comment by AbhishekPandey16** [comment]
Hi, 

Can anyone please help me here ???

**Comment by jariq** [comment]
I'm closing this issue because `SignedCms` class is not related to this project.
