### ISSUE TITLE
CADES-BES Signature 

### ISSUE THREAD

**Issue by pratik-agrawalla** [jariq/Pkcs7SignatureGenerator#5]
Hi, I want to generate CADES-BES signature . I have a precomputed signature from HSM Key vault. I want to create a CADES-BES structure that contains it. With this code i am getting CMS type signature and it is not supported as per my requirement. What is the best way to convert it into CADES-BES type signature ?

**Comment by ahmed25445** [comment]
which type of HSM you used?

**Comment by engahmedsabry** [comment]
hsm -pkcs11

**Comment by jariq** [comment]
Closing as off-topic.
